# .github/workflows/main.yml
name: Build and Deploy Supplier-API to Azure VM

on:
  push:
    branches: [ "main" ]
    paths:
      - 'supplier-api/**' 

jobs:
  build_and_push_to_acr:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./supplier-api 
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/supplier-api:latest

  deploy_to_vm:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest
    needs: build_and_push_to_acr 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_SSH_HOST }}
        username: ${{ secrets.VM_SSH_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # az login --service-principal -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          
          docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

          docker compose down --remove-orphans
          
          #cd ~
          #mkdir -p final-project/supplier-api

          echo '${{ secrets.DOCKER_COMPOSE_CONTENT }}' > ~/final-project/docker-compose.yml

          cd ~/final-project

          docker compose pull

          docker compose up -d --no-deps supplier-api